services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/postgres?schema=public
  db:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
volumes:
  postgres:
    name: fordham-db